<div class="container standart-space">
    <div class="row">

        <div class="col-lg-4 col-lg-offset-4 registration-margin">
            <div class="error-valid"><?=$error?></div>

            <form role="form" name="adm-form" method="post" action="admin/login">
                <div class="form-group">
                    <label>Login: </label>
                    <input type="text" class="form-control" name="adm-login">
                </div>
                <div class="form-group">
                    <label for="pwd">Password:</label>
                    <input type="password" class="form-control" name="adm-pass">
                </div>
                <button type="submit" class="btn btn-default">Войти</button>
            </form>

        </div>
    </div>
</div>
