<div class="panelcl">
    <ul class="pagination">
        <li><a href="<?php echo "http://".$_SERVER['SERVER_NAME'];?>">Главная</a></li>
        <li><a href="<?php echo "http://".$_SERVER['SERVER_NAME'].'/admin';?>">Пользователи</a></li>
        <li class="active"><a href="<?php echo "http://".$_SERVER['SERVER_NAME'].'/categories';?>">Категории</a></li>
        <li><a href="<?php echo "http://".$_SERVER['SERVER_NAME'].'/categories/show';?>">Объявления</a></li>
    </ul>
    <form class="form-inline" role="form" action="/admin/add-cat" method="post">
        <div class="form-group">
            <label for="text">Имя категории: </label>
            <input type="text" name="name" class="form-control" placeholder="name" required>
        </div>
        <div class="form-group">
            <label for="text">Описание категории:</label>
            <input type="text" name="desc" class="form-control" placeholder="description" required>
        </div>
        <button type="submit" class="btn btn-default">Добавить</button>
    </form>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name category</th>
        <th>Descripition</th>
        <th>Count</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($row as $tt): ?>
        <tr>
            <td><?php echo $tt["id"]; ?></td>
            <td><?php echo $tt["name"]; ?></td>
            <td><?php echo $tt['description']; ?></td>
            <td><?php echo $tt['count1']; ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>