<?php include_once 'menu.phtml';?>

<div class="container">
    <form class="form-inline" role="form" action="/admin/add-cat" method="post">
        <div class="form-group">
            <input type="text" name="name" class="form-control" placeholder="Имя категории" required>
        </div>
        <div class="form-group">
            <input type="text" name="description" class="form-control" placeholder="Описание категории" required>
        </div>
        <button type="submit" class="btn btn-default">Добавить</button>
        <div class="checkbox">
            <label><input type="checkbox" name="checkbox" value="1">Подкатегория</label>
        </div>
            <select name="pid" class="form-control">
                <?php foreach ($categories as $v):?>
                    <option value="<?php echo $v['id']?>"><?php echo $v['name']?></option> <?php endforeach; ?>
        </select>
    </form>
    <div class="row">
        <div class="span3 offset2"><?php echo $items; ?></div>
    </div>
</div>
