<div class="container standart-space">
    <div class="row">

        <div class="col-lg-4 col-lg-offset-4 registration-margin">
            <div class="error-valid"><?= $error ?></div>

            <form role="form" action="/admin/reg" method="post">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Логин администратора" name="login">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Пароль администратора">
                </div>
                <button type="submit" class="btn btn-default">Войти</button>
            </form>
        </div>
    </div>
</div>
