<div class="col-md-2">
    <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#">Admin menu</a></li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Объявления
                <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="<?php echo "http://" . $_SERVER['SERVER_NAME'] . '/categories/show/0'; ?>">Показать
                        все</a></li>
                <?php foreach ($menu as $m): ?>
                    <li><a href="<?php echo "http://" . $_SERVER['SERVER_NAME'] . '/categories/show/' . $m['id']; ?>">категория: <?php echo $m['name']; ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
        <li><a href="<?php echo "http://" . $_SERVER['SERVER_NAME'] . '/admin'; ?>">Пользователи</a></li>
        <li><a href="<?php echo "http://" . $_SERVER['SERVER_NAME'] . '/categories'; ?>">Категории</a></li>
    </ul>
</div>