<?php include_once 'menu.phtml'; ?>
<div class="container">
    <div class="col-lg-12">
        <table class="table table-striped" id="result"></table>
        <form class="form-inline my_form_adm" role="form">
            <div class="form-group">
                <label for="text">Поиск</label>
                <input type="text" name="desc" class="form-control input-sch"
                       placeholder="Логин пользователя, заголовок публикации или категорию" size="60" required>
            </div>
            <button type="submit" class="active">Search</button>
        </form>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Логин</th>
                <th>Телефон</th>
                <th>Статус</th>
                <th>Опубликовано</th>
                <th>Дата регистрации</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($row as $tt): ?>
                <tr>
                    <td><?php echo $tt["login"]; ?></td>
                    <td><?php echo $tt["phone"]; ?></td>
                    <td><?php echo $tt["status"]; ?></td>
                    <td><?php echo $tt["caunt"]; ?></td>
                    <td><?php echo $tt["date_create"]; ?></td>
                    <td>
                        <a href="/admin/user-page/<?php echo $tt["id"]; ?>">SHOW </a>
                        <?php if ($tt['status'] == 'banned'): ?>
                            <a href="/admin/unban/<?php echo $tt["id"]; ?>"><strong>UNBAN</strong></a>
                        <?php else: ?>
                            <a href="/admin/ban/<?php echo $tt["id"]; ?>"><strong>BAN</strong></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


if(isset($_POST['per_cat'])) {
$arr = $_POST['add'];
while (list($key, $value) = each($arr)) {
$this->db->insert('property_cats', ['category_id' => intval($value), 'property_id' => $key]);
}
$id = (int)array_shift($arr);
header("Location: /categories/property/{$id}");
}
if(isset($_POST['add_cat'])) {
$property_name = $_POST['property_name'];
$property_values = json_encode($_POST['property_values']);
$property_type = $_POST['property_type'];
$this->db->insert('properties', ['name' => $property_name, 'params' => $property_values, 'type' => $property_type]);
header("Location: /categories");
}