<script type="text/javascript">
    $(document).ready(function(){
        $("#btn").click(function(){
            var sa = $("#schlog").val();
            $.post("http://site.om/admin/search",
                {
                    search: sa
                }, function(data)
                {
                    $('#my_p').html(data);
                });
        });
    })
</script>
<p id="my_p"></p>
<div>
    <input type="text" id="schlog" size="20" placeholder="login">
    <button id="btn">search</button>
        <table class="table table-bordered">
        <thead>
        <tr bgcolor="aqua">
            <th>Логин</th>
            <th>Телефон</th>
            <th>Статус</th>
            <th>Опубликовано</th>
            <th>Дата регистрации</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($row as $tt): ?>
            <tr>
                <td><?php echo $tt["login"]; ?></td>
                <td><?php echo $tt["phone"]; ?></td>
                <td><?php echo $tt["status"]; ?></td>
                <td><?php echo $tt["caunt"]; ?></td>
                <td><?php echo $tt["date_create"]; ?></td>
                <td>
                    <a href="/admin/show/<?php echo $tt["id"]; ?>">Псмотреть</a>
                    <?php if($tt['status']=='banned'):?>
                        <a href="/admin/unban/<?php echo $tt["id"]; ?>">Разблокировать</a>
                    <?php else:?>
                        <a href="/admin/ban/<?php echo $tt["id"]; ?>">Заблокировать</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>