<?php include_once 'menu.phtml'; ?>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form class="form-inline my_form_adm" role="form">
                <div class="form-group">
                    <label for="text">Поиск</label>
                    <input type="text" name="desc" class="form-control input-sch"
                           placeholder="Логин пользователя, заголовок публикации или категорию" required>
                </div>
                <button type="submit" class="active sch-act">Search</button>
            </form>
            <div class="col-md-4" id="result"></div>
        </div>
        <div class="col-md-4">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Login</th>
                    <th>Phone</th>
                    <th>Ads</th>
                    <th>Registered</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($row as $tt): ?>
                    <tr>
                        <td><?php echo $tt["login"]; ?></td>
                        <td><?php echo $tt["phone"]; ?></td>
                        <td><?php echo $tt["caunt"]; ?></td>
                        <td><?php echo $tt["date_create"]; ?></td>
                        <td>
                            <a href="/admin/user-page/<?php echo $tt["id"]; ?>">SHOW </a>
                            <?php if ($tt['status'] == 'banned'): ?>
                                <a href="/admin/unban/<?php echo $tt["id"]; ?>"><strong>UNBAN</strong></a>
                            <?php else: ?>
                                <a href="/admin/ban/<?php echo $tt["id"]; ?>"><strong>BAN</strong></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>