<div>
    <ul class="breadcrumb">
        <li><a href="<?php echo "http://".$_SERVER['SERVER_NAME'];?>">Главная</a> <span class="divider">/</span></li>
        <li><a href="<?php echo "http://".$_SERVER['SERVER_NAME'].'/admin';?>">Панель администратора</a> <span class="divider">/</span></li>
        <li class="active">Профиль юзера</li>
    </ul>
<table class="table table-bordered">
    <thead>
    <tr bgcolor="aqua">
        <th>#</th>
        <th>Логин</th>
        <th>Статус</th>
        <th>Имя</th>
        <th>Почта</th>
        <th>Роль</th>
        <th>Дата регистрации</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($row as $tt): ?>
        <tr>
            <td><?php echo $tt["id"]; ?></td>
            <td><?php echo $tt["login"]; ?></td>
            <td><?php echo $tt["status"]; ?></td>
            <td><?php echo $tt["name"]; ?></td>
            <td><?php echo $tt["email"]; ?></td>
            <td><?php echo $tt["role"]; ?></td>
            <td><?php echo $tt["create_time"]; ?></td>
            <td>
                <a href="/admin/show/<?php echo $tt["id"]; ?>">Псмотреть</a>
                <?php if($tt['status']=='banned'):?>
                    <a href="/admin/unban/<?php echo $tt["id"]; ?>">Разблокировать</a>
                <?php else:?>
                    <a href="/admin/ban/<?php echo $tt["id"]; ?>">Заблокировать</a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>