<?php include_once 'menu.phtml';?>

<div class="container">
<table class="table table-striped">
    <thead>
    <tr>
        <th>Title</th>
        <th>Text</th>
        <th>name</th>
        <th>Date_create</th>
        <th>login</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($row as $tt): ?>
        <tr>
            <td><?php echo $tt["title"]; ?></td>
            <td><?php echo $tt["text"]; ?></td>
            <td><?php echo $tt["name"]; ?></td>
            <td><?php echo $tt['date_create']; ?></td>
            <td>
                <strong>
                    <a href="<?php echo "http://".$_SERVER['SERVER_NAME'].'/admin/user-page/'.$tt['id'];?>"><?php echo $tt['login']; ?></a>
                </strong>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

</div>