
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <title>ADC</title>
    <link href="/css/adsboard/reset.css" rel="stylesheet">
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/adsboard/basic.css" rel="stylesheet">
    <link href="/css/adsboard/menu.css" rel="stylesheet">

</head>
<body>
<div class="container container-lg-height">
    <div class="row">
        <div class="col-lg-2   text-center col-lg-height col-middle">
            <h1>ADSboard</h1>
        </div>

        <div class="col-lg-4  text-left col-lg-height col-middle">
        <div class="btn-group-lg">
            <a class="btn btn-default button" href="/">Home</a>
            <a class="btn btn-default button" href="/about">About</a>
            <a class="btn btn-default " href="/payment-plan">Payment Plan</a>
        </div>
        </div>

        <?php if(!empty($user['login'])){?>
        <div class="col-lg-2 col-lg-push-1 text-center col-lg-height col-middle">
            <a class="btn-link" href="/profile"><?=$user['login']?></a>
        </div>
        <div class="col-lg-2 col-lg-push-1 text-center col-lg-height col-middle">
            <a href="/logout" class="btn-link">Logout</a>
        </div>
        <?php }else{ ?>

        <div class="col-lg-2 col-lg-push-1 text-center col-lg-height col-middle">
            <a class="btn btn-lg" href="/registration">Registration</a>
        </div>
        <div class="col-lg-2 text-center col-lg-height col-middle">
            <a class="btn btn-lg" href="/login">Sign in</a>
        </div>
        <?php }?>
    </div>
</div>
<footer class="container navbar-bottom">
<hr>
    <p>&copy; Company 2014 <a class="btn-link" href="/contact-us">Contact us</a></p>

</footer></body></html>