
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title><?=$title?></title>

    <link href="/css/adsboard/reset.css" rel="stylesheet">

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <link href="/css/adsboard/basic.css" rel="stylesheet">

    <link href="/css/adsboard/menu.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<div class="container container-lg-height">
    <div class="row">
        <div class="col-lg-2   text-center col-lg-height col-middle">
            <h1>ADSboard</h1>
        </div>

        <div class="col-lg-4  text-left col-lg-height col-middle">
        <div class="btn-group-lg">
            <a class="btn btn-default button" href="/">Home</a>
            <a class="btn btn-default button" href="/about">About</a>
            <a class="btn btn-default " href="/payment-plan">Payment Plan</a>
        </div>
        </div>

        <div class="col-lg-2 col-lg-push-1 text-center col-lg-height col-middle">
            <a class="btn btn-lg" href="/registration">Registration</a>
        </div>
        <div class="col-lg-2 text-center col-lg-height col-middle">
            <a class="btn btn-lg" href="/login">Sign in</a>
        </div>
    </div>

</div>
<div class="container standart-space">
    <div class="row">
        <div class="col-lg-6">
            <div class="well well-lg">

                <div class="row">
                    <div class="col-lg-6">
                        <h1>New Ads</h1>
                    </div>

                    <div class="col-lg-6 text-right">

                        <select class="selectpicker btn btn-default" name="category">
                            <!--Добавить с помощью цикла php категории с бд-->
                            <option value="1">1</option>
                        </select>

                    </div>

                </div>
                <form role="form" action="/add-ads" method="post">
                    <div class="form-group">
                        <input type="text" class="form-control" id="InputName" placeholder="Ads Title" name="title">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" id="descField" rows="15" placeholder="Your Comments" name="description"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="InputName" placeholder="Phone" name="title">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="InputName" placeholder="Name" name="name">
                    </div>

                    <button type="submit" class="btn btn-default">Create new Ads</button>
                </form>
            </div>
        </div>
    </div>
</div>

    <footer class="container navbar-fixed-bottom">
    <hr>
        <p>&copy; Company 2014 <a class="btn-link" href="/contact-us">Contact us</a></p>

    </footer>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>




</body>
</html>
