<section class="edit">
    <h2>Edit</h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as indicated below.
        </p>
    <?php endif ?>

    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL,
        array('controller'=>'Users', 'action' => 'edit')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>

    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('name')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('name'));
            echo $this->formElementErrors($form->get('name'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('email')); ?>
        </dt>
        <dd><?php
            echo $this->formElement($form->get('email'));
            echo $this->formElementErrors($form->get('email'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('old_password'));
            ?></dt>
        <dd><?php
            echo $this->formElement($form->get('old_password'));
            echo $this->formElementErrors($form->get('old_password'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('new_password'));
            ?></dt>
        <dd><?php
            echo $this->formElement($form->get('new_password'));
            echo $this->formElementErrors($form->get('new_password'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('confirm_password')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('confirm_password'));
            echo $this->formElementErrors($form->get('confirm_password'));
            ?></dd>
        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?></dd>
    </dl>

    <?php echo $this->form()->closeTag() ?>
</section>
