<div class="container">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4 standart-space">
            <form role="form" class="form" action="/contact-us" method="post">

                <div class="form-group">
                    <label for="InputName">Name</label>
                    <input type="text" class="form-control" id="InputName" placeholder="Name" name="name">
                </div>
                <div class="form-group">
                    <label for="InputEmail">Email</label>
                    <input type="email" class="form-control" id="InputEmail" placeholder="Email" name="email">
                </div>
                <div class="form-group">
                    <label for="descField">Description</label>
                    <textarea class="form-control" id="descField" rows="10" placeholder="Your Comments" name="description"></textarea>
                </div>
                    <button type="submit" class="btn btn-default" name="contact" value="contact">Send</button>
            </form>
        </div>
    </div>
    </div>