<div class="container container-lg-height">
    <div class="row">
        <div class="col-lg-2   text-center col-lg-height col-middle">
            <h1>ADSboard</h1>
        </div>

        <div class="col-lg-4  text-left col-lg-height col-middle">
            <div class="btn-group-lg">
                <a class="btn btn-default button" href="/">Home</a>
                <a class="btn btn-default button" href="/about">About</a>
                <a class="btn btn-default " href="/payment-plan">Payment Plan</a>
            </div>
        </div>

        <div class="col-lg-2 col-lg-push-1 text-center col-lg-height col-middle">
            <a class="btn btn-lg" href="/registration">Registration</a>
        </div>
        <div class="col-lg-2 text-center col-lg-height col-middle">
            <a class="btn btn-lg" href="/login">Sign in</a>
        </div>
    </div>

</div>