<div class="container standart-space" xmlns="http://www.w3.org/1999/html">
    <h1><?=$title?></h1>
    <div class="row">
            <div class="col-lg-5">
                <form class="form-inline myform2" action="/profile/search" method="post">
                    <div class="form-group">
                        <input type="text" class="form-control input-lg" autocomplete="off" placeholder="Search ads" name="search" id="search_box">
                        <ul id="ads_id" class="list-group"></ul>
                    </div>
<!--                    <button type="submit" id="search_button" class="btn btn-primary btn-lg">Search</button>-->
                </form>

            </div>
        </div>
</div>
<div class="container">

        <div id="results">
        <?php foreach($dbinfo as $vals):?>
            <div class="col-lg-12">
                <div class="panel panel-primary ">
                    <div class="ads-style panel-heading">
                        <h2><a href="/show/<?=$vals['ads_id']?>"><?=$vals['ads_title']?></a></h2>
<!--                        <h2>--><?//=$vals['ads_title']?><!--</h2>-->
                    </div>
                    <div class="panel-body">
                        <?=$vals['ads_text']?>
                    </div>
                    <div class="ads-style panel-footer">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-lg-8" style="padding-left:0px">
                                    <span class="ads-font">Category: <a style="color: inherit" href="/category/<?=$vals['cat_id']?>"><?=$vals['categories_name']?></a></span>
                                    <span class="ads-font">Name: </span><?=$vals['user_name']?>
                                    <span class="ads-font">Phone: </span><?=$vals['users_phone']?>
                                    <span class="ads-font">Date: </span><?=$vals['ads_date_create']?>
                                </div>
                                <div class="col-lg-4 text-right" style="padding-right:0px">
                                    <a href="/show/<?=$vals['ads_id']?>" class="btn btn-default btn-sm">Read More...</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
        </div>
</div>