<div class="container standart-space">
    <h1><?=$title?></h1>
    <div class="row">
            <div class="col-lg-5">
                <form class="form-inline" action="/profile/search" method="post">
                    <div class="form-group">
                        <input type="text" class="form-control input-lg"  placeholder="Search ads" name="search" id="search_box">
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg">Search</button>
                </form>
            </div>
        <div id="results">
        <?php foreach($dbinfo as $vals):?>
            <div class="col-lg-12">
                <div class="panel panel-primary ">
                    <div class="ads-style panel-heading">
                        <h2><?=$vals['ads_title']?></h2>
                    </div>
                    <div class="panel-body">
                        <?=$vals['ads_text']?>
                    </div>
                    <div class="ads-style panel-footer">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-lg-8" style="padding-left:0px">
                                    <span class="ads-font">Category: </span><?=$vals['categories_name']?>
                                    <span class="ads-font">Name: </span><?=$vals['user_name']?>
                                    <span class="ads-font">Phone: </span><?=$vals['users_phone']?>
                                    <span class="ads-font">Date: </span><?=$vals['ads_date_create']?>
                                </div>
                                <div class="col-lg-4 text-right" style="padding-right:0px">
                                    <a href="/show/<?=$vals['ads_id']?>" class="btn btn-default btn-sm">Read More...</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach;?>
        </div>
    </div>
</div>