<nav>
    <?php if($pages>1){?>

        <ul class='pagination pagination-lg'>


            <li class="<?=($page==1)?'disabled':''?>"><a href="/profile?page=<?php echo ($page>1)?($page-1):1;?>">&laquo;</a></li>

            <?php if($pages<=$window+1){?>

                <?php  for($i=1;$i<$pages+1;$i++){?>
                    <li class="<?=($page==$i)?'active':''?>"><a href="/profile?page=<?=$i?>"><?=$i?></a></li>
                <?php } ?>

            <?php }elseif($page>=1&&$page<$window){?>



                <?php for($i=1;$i<$window+1;$i++){?>
                    <li class="<?=($i==$page)?'active':''?>"><a href="/profile?page=<?=$i?>"><?=$i?></a></li>
                <?php } ?>


                <li><a href="/profile?page=<?=$page+$window-1?>">...</a></li>

                <li><a href="/profile?page=<?=$pages?>"><?=$pages?></a></li>

            <?php }elseif($page>=2&&$window<=$page&&$page<$pages-$windowCentr){ ?>



                <li><a href="/profile?page=<?=1?>"><?=1?></a></li>

                <?php if($page-$windowCentr-1!=1){?>
                    <li><a href="/profile?page=<?=(($page-$window)>0?$page-$window:1)?>">...</a></li>
                <?php }?>
                <?php for($i=$page-$windowCentr;$i<$page;$i++){?>
                    <li class="<?=($i==$page)?'active':''?>"><a href="/profile?page=<?php echo ($i>1)?$i:1;?>"><?php echo ($i>1)?$i:1;?></a></li>
                <?php } ?>
                <li class="active"><a href="/profile?page=<?php echo $page?>"><?php echo $page?></a></li>
                <?php for($i=$page+1;$i<=$page+$windowCentr;$i++){?>
                    <li class="<?=($i==$page)?'active':''?>"><a href="/profile?page=<?php echo ($pages>$i)?$i:$pages;?>"><?php echo ($pages>$i)?$i:$pages;?></a></li>
                <?php } ?>
                <?php if($page+$windowCentr+1!=$pages){?>
                    <li><a href="/profile?page=<?=(($page+$window)<=$pages?$page+$window:$pages)?>">...</a></li>
                <?php }?>

                <li><a href="/profile?page=<?=$pages?>"><?=$pages?></a></li>



            <?php }elseif($page>=$pages-$window){?>


                <li><a href="/profile?page=<?=1?>"><?=1?></a></li>
                <li><a href="/profile?page=<?=(($page-$window)>0?$page-$window:1)?>">...</a></li>


                <?php for($i=$pages-$window;$i<$pages+1;$i++){?>
                    <li class="<?=($i==$page)?'active':''?>"><a href="/profile?page=<?=$i?>"><?=$i?></a></li>
                <?php } ?>

            <?php }?>





            <li class="<?=($page==$pages)?'disabled':''?>"><a href="/profile?page=<?php echo ($pages>$page)?($page+1):$pages;?>">&raquo;</a></li>

        </ul>
    <?php }?>
    <script>
        $('ul.pagination li.disabled,li.active a').click(function(e){
            return false;
        });
    </script>
</nav>