<div class="container standart-space">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h3>Comments</h3>
            <button id="addNewComment">Add comment</button>
            <?php if (empty($comments)) { ?>
                <!--            <div style="text-align: center">No results</div>-->
                <hr>
            <?php } else {
                echo $comments;
            } ?>
            <br />
            <span id="show-more"><a href="">show more</a></span>
        </div>

    </div>

    <div class="row">
        <div class="col-lg-7 col-lg-offset-2 registration-margin">
            <div id="addCommentContainer">
                <p class="title-comment">Add new comment</p>

                <form id="addCommentForm" method="post" action="add-comment">
                    <div id="comment-d">

                        <div class="form-group">
                            <input type="text" name="ad_id" id="id" hidden="hidden"
                                   value="<?= $dbinfo[0]['ads_id'] ?>"/>
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="pid" value="0" id="pid">
                            <span class="text-comment">Name: <?= \application\classes\Session::get('login') ?></span>
                            <span class="error"></span>
                            <textarea name="body" id="body" cols="20" class="form-control" rows="6"></textarea>
                        </div>
                        <input type="submit" id="submit" class="submit" value="Send"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
