<link rel="stylesheet" href="/css/file-upload/style.css">

<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="/css/file-upload/jquery.fileupload.css">
<link rel="stylesheet" href="/css/file-upload/jquery.fileupload-ui.css">
<!-- CSS adjustments for browsers with JavaScript disabled -->
<noscript><link rel="stylesheet" href="/css/file-upload/jquery.fileupload-noscript.css"></noscript>
<noscript><link rel="stylesheet" href="/css/file-upload/jquery.fileupload-ui-noscript.css"></noscript>
<div class="container">
    <div class="page-header">
        <h2><a class="btn-link" href="/profile"><?=$user['login']?></a> <small>Profile</small> <a href="/profile/edit" class="btn btn-default btn-xs">Edit</a></h2>
    </div>
</div>
<div class="container">

<div class="row">
    <div class="col-lg-6">
        <h1>Edit Ads</h1>
    </div>
</div>

    <div class="row ads-gap">
        <div class="col-lg-6">

            <div class="container">

                <form id="fileupload" method="POST" enctype="multipart/form-data">
                    <div class="col-lg-6">
                        <div class="row">
                            <div id="dropzone" class="well well-lg">
                                <div class="row files"></div>
                            </div>
                        </div>
                        <span class="btn btn-default fileinput-button hide">
                            <i class="glyphicon glyphicon-plus"></i>
                            <span>Add files...</span>
                            <input type="file" name="files[]" multiple>
                        </span>
                    </div>
                </form>
            </div>

            <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
                <div class="slides"></div>
                <h3 class="title"></h3>
                <a class="prev">‹</a>
                <a class="next">›</a>
                <a class="close">×</a>
                <a class="play-pause"></a>
                <ol class="indicator"></ol>
            </div>

            <script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <div class="template-upload fade col-lg-4">
        <div>
            <span class="preview"></span>
        </div>
        <div>


            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
            <div class="progress progress-striped active col-lg-6" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
                <button class="btn btn-ex btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                </button>
            {% } %}
        </div>
    </div>
{% } %}
</script>
            <!-- The template to display files available for download -->
            <script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <div class="template-download well well-sm fade col-lg-4">
        <div>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}" width="150" height="150"></a>
                {% } %}
            </span>
        </div>
        <div class="img-name col-lg-10  text-center">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>
                        {% if (file.name.length>15) { %}
                            {%=file.name.slice(0,14)+'...'%}
                        {% }else{ %}
                            {%=file.name%}
                        {% } %}
                    </a>
                {% } %}
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </div>
        <div class="delete-button col-lg-2 col-lg-pull-1">
            {% if (file.deleteUrl) { %}
                <button class="btn btn-default btn-sm delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                </button>
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </div>

    </div>
{% } %}
</script>
                <script src="/js/file-upload/vendor/jquery.ui.widget.js"></script>
                <!-- The Templates plugin is included to render the upload/download listings -->
                <script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
                <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
                <script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
                <!-- The Canvas to Blob plugin is included for image resizing functionality -->
                <script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
                <!-- blueimp Gallery script -->
                <script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
                <!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
                <script src="/js/file-upload/jquery.iframe-transport.js"></script>
                <!-- The basic File Upload plugin -->
                <script src="/js/file-upload/jquery.fileupload.js"></script>
                <!-- The File Upload processing plugin -->
                <script src="/js/file-upload/jquery.fileupload-process.js"></script>
                <!-- The File Upload image preview & resize plugin -->
                <script src="/js/file-upload/jquery.fileupload-image.js"></script>
                <!-- The File Upload validation plugin -->
                <script src="/js/file-upload/jquery.fileupload-validate.js"></script>
                <!-- The File Upload user interface plugin -->
                <script src="/js/file-upload/jquery.fileupload-ui.js"></script>
                <!-- The main application script -->
                <script src="/js/file-upload/edit-img.js"></script>
                <!-- The XDomainRequest Transport is included for cross-domain file deletion for IE 8 and IE 9 -->
                <!--[if (gte IE 8)&(lt IE 10)]>
                <script src="/js/file-upload/cors/jquery.xdr-transport.js"></script>
                <![endif]-->










        </div>




        <div class="col-lg-5 col-lg-push-1">



                <form role="form" class="text-left" action="/profile/ads-edit/<?=$dbinfo[0]['ads_id']?>" method="post">





                    <div class="form-group <?php echo !empty($errors['title'])?'has-error':''?>">
                        <label for="InputName">Ads Title</label>
                        <input type="text" class="form-control" id="InputName" placeholder="Ads Title" name="title" value="<?=$dbinfo[0]['title']?>">
                        <div class="text-right">
                            <span class="text-danger"><?php echo !empty($errors['title'])?$errors['title']:''?></span>
                        </div>
                    </div>
                    <div class="form-group <?php echo !empty($errors['text'])?'has-error':''?>">
                        <label for="descField">Description</label>
                        <textarea class="form-control" id="descField" rows="10" placeholder="Your Comments" name="text" ><?=$dbinfo[0]['text']?></textarea>
                        <div class="text-right">
                            <span class="text-danger"><?php echo !empty($errors['text'])?$errors['text']:''?></span>
                        </div>
                    </div>


                        <div class="col-lg-6 text-left">
                            <button  class="btn btn-default add-img">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>Add Img...</span>
                            </button>
                        </div>
                        <div class="col-lg-6 text-right">
                            <button type="submit" class="btn btn-default">Save changes</button>
                        </div>





                </form>


    </div>
</div>
<script>
    $('.add-img').click(function(){
        $('.fileinput-button input').trigger('click');
        return false;
    });
</script>



