<div class="container">
    <div class="page-header">
        <h2><a class="btn-link" href="/profile">UserLogin</a> <small>Profile</small> <a href="/profile/edit" class="btn btn-default btn-xs">Edit</a></h2>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-push-3">
            <div class="well well-lg">

                <div class="row">
                    <div class="col-lg-6">
                        <h1>Edit Ads</h1>
                    </div>

                </div>

                <form role="form" class="text-left" action="/profile/ads-edit/<?=$dbinfo['id_ad']?>" method="post">
                    <div class="form-group">
                        <label for="InputName">Ads Title</label>
                        <input type="text" class="form-control" id="InputName" placeholder="Ads Title" name="title" value="<?=$dbinfo['title']?>">
                        <div class="text-right">
                            <span class="text-danger"><?php echo !empty($errors['title'])?$errors['title']:''?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="descField">Description</label>
                        <textarea class="form-control" id="descField" rows="15" placeholder="Your Comments" name="text" ><?=$dbinfo['text']?></textarea>
                        <div class="text-right">
                            <span class="text-danger"><?php echo !empty($errors['text'])?$errors['text']:''?></span>
                        </div>
                    </div>

                    <div class="text-right">
                        <button type="submit" class="btn btn-default">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>