<link rel="stylesheet" href="/css/file-upload/style.css">

<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="/css/file-upload/jquery.fileupload.css">
<link rel="stylesheet" href="/css/file-upload/jquery.fileupload-ui.css">
<!-- CSS adjustments for browsers with JavaScript disabled -->
<noscript><link rel="stylesheet" href="/css/file-upload/jquery.fileupload-noscript.css"></noscript>
<noscript><link rel="stylesheet" href="/css/file-upload/jquery.fileupload-ui-noscript.css"></noscript>
<div class="container">
    <div class="page-header">
        <h2><a class="btn-link" href="/profile"><?=$user['login']?></a> <small>Profile</small> <a href="/profile/edit" class="btn btn-default btn-xs">Edit</a></h2>
    </div>
</div>
<div class="container">

<div class="row">
    <div class="col-lg-6">
        <h1>Edit Ads</h1>
    </div>
</div>

    <div class="row ads-gap">


        <div class="col-lg-6">



                <div class="container">

                    <!-- The file upload form used as target for the file upload widget -->
                    <form id="fileupload"  method="POST" enctype="multipart/form-data">
                        <!-- Redirect browsers with JavaScript disabled to the origin page -->
                        <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
                        <!-- The table listing the files available for upload/download -->
                        <div class="col-lg-6">
                            <h3  style="display: inline">Ads Img's:</h3>
                            <table role="presentation" class="table table-striped ads-gap"><tbody class="files"></tbody></table>
                        </div>
                        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
                        <div class="row fileupload-buttonbar">
                            <div class="col-lg-7">
                                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button hidden">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add Img...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                                <!--<button type="submit" class="btn btn-primary start">
                                    <i class="glyphicon glyphicon-upload"></i>
                                    <span>Start upload</span>
                                </button>-->
                                <!--<button type="reset" class="btn btn-warning cancel">
                                    <i class="glyphicon glyphicon-ban-circle"></i>
                                    <span>Cancel upload</span>
                                </button>-->
                                <button type="button" class="btn btn-danger delete hidden">
                                    <i class="glyphicon glyphicon-trash"></i>
                                    <span>Delete All</span>
                                </button>
                                <input type="checkbox" hidden="hidden" class="toggle" checked>
                                <!-- The global file processing state -->
                                <span class="fileupload-process"></span>
                            </div>
                            <!-- The global progress state -->
                            <div class="col-lg-5 fileupload-progress fade">
                                <!-- The global progress bar -->
                                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                                </div>
                                <!-- The extended global progress state -->
                                <div class="progress-extended">&nbsp;</div>
                            </div>
                        </div>

                    </form>
                    <br>

                </div>
                <!-- The blueimp Gallery widget -->
                <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
                    <div class="slides"></div>
                    <h3 class="title"></h3>
                    <a class="prev">‹</a>
                    <a class="next">›</a>
                    <a class="close">×</a>
                    <a class="play-pause"></a>
                    <ol class="indicator"></ol>
                </div>
                <!-- The template to display files available for upload -->
                <script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled style="display:none;">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
                <!-- The template to display files available for download -->
                <script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle" hidden="hidden"  checked>
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
                <script src="/js/file-upload/vendor/jquery.ui.widget.js"></script>
                <!-- The Templates plugin is included to render the upload/download listings -->
                <script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
                <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
                <script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
                <!-- The Canvas to Blob plugin is included for image resizing functionality -->
                <script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
                <!-- blueimp Gallery script -->
                <script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
                <!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
                <script src="/js/file-upload/jquery.iframe-transport.js"></script>
                <!-- The basic File Upload plugin -->
                <script src="/js/file-upload/jquery.fileupload.js"></script>
                <!-- The File Upload processing plugin -->
                <script src="/js/file-upload/jquery.fileupload-process.js"></script>
                <!-- The File Upload image preview & resize plugin -->
                <script src="/js/file-upload/jquery.fileupload-image.js"></script>
                <!-- The File Upload validation plugin -->
                <script src="/js/file-upload/jquery.fileupload-validate.js"></script>
                <!-- The File Upload user interface plugin -->
                <script src="/js/file-upload/jquery.fileupload-ui.js"></script>
                <!-- The main application script -->
                <script src="/js/file-upload/edit-img.js"></script>
                <!-- The XDomainRequest Transport is included for cross-domain file deletion for IE 8 and IE 9 -->
                <!--[if (gte IE 8)&(lt IE 10)]>
                <script src="/js/file-upload/cors/jquery.xdr-transport.js"></script>
                <![endif]-->










        </div>








                <form role="form" class="text-left" action="/profile/ads-edit/<?=$dbinfo['id']?>" method="post">

                    <div class="col-lg-6">


                        <div class="col-lg-12">
                    <div class="form-group <?php echo !empty($errors['title'])?'has-error':''?>">
                        <label for="InputName">Ads Title</label>
                        <input type="text" class="form-control" id="InputName" placeholder="Ads Title" name="title" value="<?=$dbinfo['title']?>">
                        <div class="text-right">
                            <span class="text-danger"><?php echo !empty($errors['title'])?$errors['title']:''?></span>
                        </div>
                    </div>
                    <div class="form-group <?php echo !empty($errors['text'])?'has-error':''?>">
                        <label for="descField">Description</label>
                        <textarea class="form-control" id="descField" rows="10" placeholder="Your Comments" name="text" ><?=$dbinfo['text']?></textarea>
                        <div class="text-right">
                            <span class="text-danger"><?php echo !empty($errors['text'])?$errors['text']:''?></span>
                        </div>
                    </div>

                    <!--<div class="form-group <?php /*echo !empty($errors['userName'])?'has-error':''*/?>">
                        <label class="control-label" for="userName">Your Name</label>
                        <input type="text" class="form-control" id="userName" placeholder="Your Name" name="userName" value="<?/*=$dbinfo['name']*/?>">
                        <span class="text-danger"><?php /*echo !empty($errors['userName'])?$errors['userName']:''*/?></span>
                    </div>

                    <div class="form-group <?php /*echo !empty($errors['userPhone'])?'has-error':''*/?>">
                        <label class="control-label" for="userPhone">Your Phone</label>
                        <input type="text" class="form-control" id="userPhone" placeholder="Your Phone" name="userPhone" value="<?/*=$dbinfo['phone']*/?>">
                        <span class="text-danger"><?php /*echo !empty($errors['userPhone'])?$errors['userPhone']:''*/?></span>
                    </div>-->

                        </div>
                    <!--<div class="text-right">
                        <button type="submit" class="btn btn-default">Save changes</button>
                    </div>-->

                        <div class="col-lg-6 text-left">
                            <button  class="btn btn-default add-img">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>Add Img...</span>
                            </button>
                            <button  class="btn btn-default delete-img">
                                <i class="glyphicon glyphicon-trash"></i>
                                <span>Delete All</span>
                            </button>
                        </div>
                        <div class="col-lg-6 text-right">
                            <button type="submit" class="btn btn-default">Save changes</button>
                        </div>




                        </div>
                </form>


    </div>
</div>
<script>
    $('.add-img').click(function(){
        $('.fileinput-button input').trigger('click');
        return false;
    });
    $('.delete-img').click(function(){
        $('.fileupload-buttonbar .delete').trigger('click');
        return false;
    });
</script>



