<div class="container standart-space">
    <div class="row">

        <div class="col-lg-4 col-lg-offset-4 registration-margin">
            <div class="error-valid"><?=$error?></div>

            <form role="form" action="/login" method="post">

                <div class="form-group">
                    <label for="InputLogin">Login</label>
                    <input type="text" class="form-control" id="InputLogin" placeholder="Login" name="login">
                </div>

                <div class="form-group">
                    <label for="InputPassword">Password</label>
                    <input type="password" class="form-control" id="InputPassword" placeholder="Password" name="password">
                </div>

                <div class="row">
                    <div class="col-lg-6 col-lg-height col-bottom">
                        <div class="checkbox-inline">
                            <label><input type="checkbox" name="rememberMe" value="rememberMe">Remember Me</label>
                        </div>
                    </div>

                    <div class="col-lg-6 col-lg-push-4 text-right col-lg-height col-bottom">
                        <button type="submit" class="btn btn-default ">Sign in</button>
                    </div>

                    <div class="col-lg-6 text-right col-lg-offset-6" style="padding-right: 0px; margin-top: 10px;">
                        <a class="btn btn-link" href="/restore-password">Forgot password?</a>
                    </div>
                </div>
            </form>
        </div>

    </div>
</div>
