<div class="container">
    <div class="row col-lg-4">
        <p class="lead">Авторизация</p>
    <form role="form" action="/login" method="post">

        <div class="form-group">
            <label for="InputLogin">Логин</label>
            <input type="text" class="form-control" id="InputLogin" placeholder="Имя" name="login" required>
        </div>
        <div class="form-group">
            <label for="InputPassword">Пароль</label>
            <input type="password" class="form-control" id="InputPassword" placeholder="Пароль" name="password1">
        </div>

        <button type="submit" class="btn btn-default">Войти</button>

    </form>
    </div>
</div>