<div class="container">
    <div class="page-header">
        <h2><a class="btn-link" href="/profile">UserLogin</a> <small>Profile</small> <a href="/profile/edit" class="btn btn-default btn-xs">Edit</a></h2>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-push-3">
            <div class="well well-lg">

                <div class="row">
                    <div class="col-lg-6">
                        <h1>New Ads</h1>
                    </div>

                    <form role="form" action="/profile/add-ads" method="post">

                        <div class="col-lg-6 text-right">

                            <span class="text-capitalize">Categories:</span>

                            <select class="selectpicker btn btn-default" name="category">
                                <?php foreach($dbinfo as $vals):?>
                                  <option value="<?=$vals['name']?>"><?=$vals['name']?></option>
                                <?php endforeach; ?>
                            </select>
                            <span class="text-danger"><?php echo !empty($errors['category'])?$errors['category']:''?></span>

                        </div>

                        <div class="col-lg-12 text-right">

                            <div class="form-group">
                                 <input type="text" class="form-control" id="InputName" placeholder="Ads Title" name="title">
                                 <span class="text-danger"><?php echo !empty($errors['title'])?$errors['title']:''?></span>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" id="descField" rows="15" placeholder="Your Comments" name="text"></textarea>
                                <span class="text-danger"><?php echo !empty($errors['text'])?$errors['text']:''?></span>
                            </div>

                        </div>

                        <div class="col-lg-12 text-right">
                            <button type="submit" class="btn btn-default">Create new Ads</button>
                        </div>
                </form>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>