<div class="container standart-space">
    <div class="row">
        <div class="col-lg-6">
            <div class="well well-lg">

                <div class="row">
                    <div class="col-lg-6">
                        <h1>New Ads</h1>
                    </div>

                    <div class="col-lg-6 text-right">

                        <select class="selectpicker btn btn-default" name="category">
                            <!--Добавить с помощью цикла php категории с бд-->
                            <option value="1">1</option>
                        </select>

                    </div>

                </div>
                <form role="form" action="/add-ads" method="post">
                    <div class="form-group">
                        <input type="text" class="form-control" id="InputName" placeholder="Ads Title" name="title">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" id="descField" rows="15" placeholder="Your Comments" name="description"></textarea>
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="InputName" placeholder="Phone" name="title">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="InputName" placeholder="Name" name="name">
                    </div>

                    <button type="submit" class="btn btn-default">Create new Ads</button>
                </form>
            </div>
        </div>
    </div>
</div>