<div class="container text-center standart-space">
    <div class="row">
        <h3><?php if(\application\classes\Session::get('countAds') == -1) {
                echo 'Unlimited';
            } else
            echo 'Remains '.\application\classes\Session::get('countAds');?> Ads</h3>
        <?php foreach($plans as $plan): ?>
        <div class="col-lg-4">
            <form role="form" action="/subsccribe-payment-plane/<?=$plan['name']?>" method="post">

                <div class="panel panel-primary">
                    <div class="panel-heading  panel-style">
                        <h1><?=$plan['name']?></h1>
                    </div>
                    <div class="panel-body">
                        <h2>$<?php echo $plan['price']; if($plan['name']!= 'free') echo '/month'; ?></h2>
                        <hr>
                        <h2><?php if ($plan['count_ads'] == -1) echo 'Unlimited'; else echo $plan['count_ads']?> ads</h2>
                    </div>
                    <input type="hidden" name="itemname" value="<?=$plan['name']?>" />
                    <input type="hidden" name="itemdesc" value="aaaaa" />
                    <input type="hidden" name="itemqty" value="1" />

                    <div class="panel-footer panel-style">
                        <!--Если не вошел-->
                        <?php if(!isset($_SESSION['login']) && $plan['id'] == 1) {?>
                            <button type="submit"  class="btn btn-primary btn-lg" name="signup" value="signup">Sign up</button>
                        <?php }else if (!isset($_SESSION['login']) && $plan['id'] != 1 ){?>
                            <button type="submit"  class="btn btn-primary btn-lg" name="buy" value="buy">Buy</button>
                        <?php }?>
                        <?php if (isset($_SESSION['login']) && $plan['id'] ==  $user['plan_id']){?>
                            <h3 style="font-size: 18px; margin-top: 16px">Current</h3>
                        <?php }else if(isset($_SESSION['login']) && $user['plan_id'] == '1'){?>

                            <button type="submit"  class="btn btn-primary btn-lg" name="upgrade" value="upgrade">Upgrade</button>
                        <?php }  if (isset($_SESSION['login']) && $user['plan_id'] == '3' && $user['plan_id'] != $plan['id']) {?>
                            <button type="submit"  class="btn btn-primary btn-lg" name="downgrade" value="downgrade">Downgrade</button>
                        <?php }else {?>
                                <?php if($user['plan_id'] == '2' && $plan['name'] == 'business'){?>
                                    <button type="submit"  class="btn btn-primary btn-lg" name="upgrade" value="upgrade">Upgrade</button>
                            <?php }?>

                            <?php if($user['plan_id'] == '2' && $plan['name'] == 'free'){?>
                                <button type="submit"  class="btn btn-primary btn-lg" name="downgrade" value="downgrade">Downgrade</button>
                            <?php }?>

                        <?php }?>

                        <!--Если вошел и  FREE-->
                    </div>
                </div>
            </form>
        </div>
        <?php endforeach;?>
    </div>
</div>
<script>
$(function() {
    $("form").on('submit', function(e) {
        var res;
        res = confirm("Are you sure?");
        console.log(res);
        if(!res)
            e.preventDefault();
    });

});
</script>