<div class="container">
    <div class="page-header">
        <h2><a class="btn-link" href="/profile"><?=$user['login']?></a> <small>Profile</small> <a href="/profile/edit" class="btn btn-default btn-xs">Edit</a></h2>
    </div>
</div>


<div class="container text-right">
    <div class="col-lg-5 text-left">
        <h3>Your Ads:</h3>
    </div>
    <div class="col-lg-5">
        <form class="form-inline myform2" action="/profile/search" method="post">
            <div class="form-group">
                <input type="hidden" name="profile" id = 'profile'>
                <input type="text" class="form-control input-lg" autocomplete="off" placeholder="Search ads" name="search" id="search_box">
                <ul id="ads_id" class="list-group text-left"></ul>
        </form>
            </div>
<!--            <button type="submit" class="btn btn-primary btn-lg">Search</button>-->

    </div>
    <div class="col-lg-2">
        <a href="/profile/add-ads" class="btn btn-default btn-lg">Add new Ads</a>
    </div>
</div>


<div class="container text-left ads">
    <div class="row">

<?php if(!empty($dbinfo)):?>
    <?php foreach($dbinfo as $vals):?>
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="ads-style panel-heading">
                    <h2><?=$vals['ads_title']?></h2>
                </div>
                <div class="panel-body">
                    <?=$vals['ads_text']?>
                </div>
                <div class="ads-style panel-footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-8" style="padding-left:0px">
                                <span class="ads-font">Category: </span><?=$vals['categories_name']?>
                                <span class="ads-font">Name: </span><?=$vals['user_name']?>
                                <span class="ads-font">Phone: </span><?=$vals['users_phone']?>
                                <span class="ads-font">Date: </span><?=$vals['ads_date_create']?>
                            </div>
                            <div class="col-lg-4 text-right" style="padding-right:0px">
                                <a href="/profile/ads-edit/<?=$vals['ads_id']?>" class="btn btn-default btn-xs">Edit</a>
                                <a href="/profile/ads-delete/<?=$vals['ads_id']?>" class="btn btn-danger btn-xs ads-del">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach;?>
<?php endif;?>
    </div>


    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 text-center">

            <?=$paginator->render()?>

        </div>
    </div>
</div>


<script>
    $(function() {
        $(".ads-del").click(function(e) {
            bootbox.confirm("Are you sure?", function(result) {
                if(result){
                    window.location.href = $('.ads-del').attr('href');
                }
            });
            e.preventDefault();
        });
    });
</script>