<div class="container">
    <div class="page-header">
        <h2><a class="btn-link" href="/profile">UserLogin</a> <small>Profile</small> <a href="/profile/edit" class="btn btn-default btn-xs">Edit</a></h2>
    </div>
</div>


<div class="container text-right">
    <div class="col-lg-5 text-left">
        <h3>Your Ads:</h3>
    </div>
    <div class="col-lg-5">
        <form class="form-inline" action="/profile/search" method="post">
            <div class="form-group">
                <input type="text" class="form-control input-lg"  placeholder="Search ads" name="search">
            </div>
            <button type="submit" class="btn btn-primary btn-lg">Search</button>
        </form>
    </div>
    <div class="col-lg-2">
        <a href="/profile/add-ads" class="btn btn-default btn-lg">Add new Ads</a>
    </div>
</div>


<div class="container text-left ads">
    <div class="row">


    <?php foreach($dbinfo as $vals):?>
        <div class="col-lg-12">
            <div class="panel panel-primary ">
                <div class="ads-style panel-heading">
                    <h2><?=$vals['ad_title']?></h2>
                </div>
                <div class="panel-body">
                    <?=$vals['ad_text']?>
                </div>
                <div class="ads-style panel-footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-8" style="padding-left:0px">
                                <span class="ads-font">Category: </span><?=$vals['categories_name']?>
                                <span class="ads-font">Name: </span><?=$vals['user_name']?>
                                <span class="ads-font">Phone: </span><?=$vals['user_phone']?>
                                <span class="ads-font">Date: </span><?=$vals['ad_date_create']?>
                            </div>
                            <div class="col-lg-4 text-right" style="padding-right:0px">
                                <a href="/profile/ads-edit/<?=$vals['ad_id_ad']?>" class="btn btn-default btn-xs">Edit</a>
                                <a id="ads-delete" href="/profile/ads-delete/<?=$vals['ad_id_ad']?>" class="btn btn-danger btn-xs">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach;?>



        <div class="col-lg-2 col-lg-push-5">
            <nav>
                <ul class="pager">
                    <li class="previous"><a href="/profile/page/(page_number)"><span aria-hidden="true">&larr;</span> Prev</a></li>
                    <li class="next"><a href="/profile/page/(page_number)">Next <span aria-hidden="true">&rarr;</span></a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

<script>
    $(function() {
        $("#ads-delete").click(function(e) {
            bootbox.confirm("Are you sure?", function(result) {
                if(result){
                    window.location.href = $('#ads-delete').attr('href');
                }
            });
            e.preventDefault();
        })


            $("html").notify(
                'Hello',
                { position:"top right" }
            );
            //$('#info').hide('fast');

    });
</script>