<div class="container">
    <div class="row col-lg-6">
        <form role="form" action="/registration" method="post">

            <div class="form-group">
                <label for="InputName">Имя</label>
                <input type="text" class="form-control" id="InputName" placeholder="Имя" name="name">
            </div>
            <div class="form-group">
                <label for="InputLogin">Логин</label>
                <input type="text" class="form-control" id="InputLogin" placeholder="Имя" name="login">
            </div>
            <div class="form-group">
                <label for="InputEmail">Email</label>
                <input type="email" class="form-control" id="InputEmail" placeholder="Введите адрес электронной почты" name="email">
            </div>
            <div class="form-group">
                <label for="InputPassword">Пароль</label>
                <input type="password" class="form-control" id="InputPassword" placeholder="Пароль" name="password1">
            </div>
            <div class="form-group">
                <label for="InputConfirmPassword">Введите еще раз пароль</label>
                <input type="password" class="form-control" id="InputConfirmPassword" placeholder="Введите еще раз пароль" name="password2">
            </div>
            <div class="form-group">
                <label for="InputPhone">Телефон</label>
                <input type="tel" class="form-control" id="InputPhone" placeholder="Введите свой телефон" name="phone">
            </div>
            <button type="submit" class="btn btn-default">Зарегистророватися</button>

            <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
        </form>
    </div>
</div>