<div class="container standart-space">
    <div class="row">
        <div class="col-lg-4 col-lg-offset-4 registration-margin">
            <form role="form" action="/restore-password" method="post">
                <h3>Введите email для восстановления пароля</h3>
                <div class="form-group">
                    <label for="InputEmail">Email</label>
                    <input type="email" class="form-control" id="InputEmail" placeholder="Email" name="email">
                </div>
                <button type="submit" class="btn btn-default" name="send" value="send">Отправить</button>
            </form>
        </div>
    </div>
</div>